### ISSUE TITLE
maybe make "try" really an expression?

### ISSUE THREAD

**Issue by pocesar** [isiahmeadows/proposal-try-expression#1]
kotlin allows you to use try as an expression:

```kt
// ? means nullable
val a: Int? = try { parseInt(input) } catch (e: NumberFormatException) { null }
```

this way, "throwing" expressions could be paired with newly-added null coalescing `??` in case catch doesn't really return anything. the good side effect that you wouldn't need extra "try await" syntax, you can use inside the expression like you normally would (the same way you can use `await` inside loops)

```js
const alwaysValue = try { await some() } catch (e) { null } ?? 'fallback'
```

this reads better, you don't need to shove variables outside of the block scope inside just to assign a variable. this is important because try also has "finally", that executes regardless of failure, and wouldn't be able to fit the way you proposed

**Comment by ljharb** [comment]
That requires an implicit completion value from the blocks, which is a massive proposal (see "do expressions").

**Comment by dead-claudia** [comment]
@pocesar This is distinctly different from my proposal here and is out of scope. You'd have better luck asking over in the [do expression proposal](https://github.com/tc39/proposal-do-expressions), and there's already two open issues on that subject there:

- https://github.com/tc39/proposal-do-expressions/issues/36
- https://github.com/tc39/proposal-do-expressions/issues/6
